use lazy_static::lazy_static;
use std::collections::HashMap;
#[derive(Hash, Eq, PartialEq)]
pub enum BuildingType {
    SmallHouse,
}
lazy_static! {
    pub static ref BUILDINGS: HashMap<BuildingType, Bitmap> = HashMap::from([(
        BuildingType::SmallHouse,
        Bitmap::from(
            "########\n
                #xxxxxx#\n
                #xxxxxx#\n
                #xxxxxx#\n
                #xxxxxx#\n
                #xxxxxx#\n
                #####x##\n"
        )
    )]);
    pub static ref LETTERS: HashMap<char, Bitmap> = HashMap::from([
        (
            'a',
            Bitmap::from(
                "xxxxxxxx\n
                xxxxxxxx\n
                ########\n
                xxxxxxx#\n
                ########\n
                #xxxxxx#\n
                ########\n"
            )
        ),
        (
            'b',
            Bitmap::from(
                "xxxxxxxx\n
                #xxxxxxx\n
                #xxxxxxx\n
                ########\n
                #xxxxxx#\n
                #xxxxxx#\n
                ########\n"
            )
        ),
        (
            'c',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        xx######\n
                        x#xxxxxx\n
                        #xxxxxxx\n
                        x#xxxxxx\n
                        xx######\n"
            )
        ),
        (
            'd',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxx#\n
                        xxxxxxx#\n
                        xxxxxxx#\n
                        xxxx####\n
                        xx#xxxx#\n
                        xxx#####\n"
            )
        ),
        (
            'e',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        xx#####x\n
                        x#xxxxx#\n
                        ########\n
                        #xxxxxxx\n
                        x#######\n"
            )
        ),
        (
            'f',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        xx####xx\n
                        x#xxxxxx\n
                        ####xxxx\n
                        x#xxxxxx\n
                        x#xxxxxx\n"
            )
        ),
        (
            'g',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        x######x\n
                        #xxxxxx#\n
                        x#######\n
                        xxxxxxx#\n
                        #######x\n"
            )
        ),
        (
            'h',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        #xxxxxxx\n
                        #xxxxxxx\n
                        #######x\n
                        #xxxxx#x\n
                        #xxxxx#x\n"
            )
        ),
        (
            'i',
            Bitmap::from(
                "xxxx#xxx\n
                        xxxxxxxx\n
                        xxxxxx#x\n
                        xxxxxx#x\n
                        xxxxxx#x\n
                        xxxxxx#x\n
                        xxxxx###\n"
            )
        ),
        (
            'j',
            Bitmap::from(
                "xxxxxx#x\n
                        xxxxxxxx\n
                        xxxxxx#x\n
                        xxxxxx#x\n
                        xxxxxx#x\n
                        xxx#xx#x\n
                        xxxx##xx\n"
            )
        ),
        (
            'k',
            Bitmap::from(
                "xxxxxxxx\n
                        x#xxxxxx\n
                        x#xx#xxx\n
                        x#x#xxxx\n
                        x##xxxxx\n
                        x#x#xxxx\n
                        x#xx#xxx\n"
            )
        ),
        (
            'l',
            Bitmap::from(
                "xxxxxxxx\n
                        x#xxxxxx\n
                        x#xxxxxx\n
                        x#xxxxxx\n
                        x#xxxxxx\n
                        x#xxxxxx\n
                        x##xxxxx\n"
            )
        ),
        (
            'm',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        xxx#xxx#\n
                        xx#x#x##\n
                        x#xxx#x#\n
                        #xxxxxx#\n
                        #xxxxxx#\n"
            )
        ),
        (
            'n',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        xx#####x\n
                        xx#xxx#x\n
                        xx#xxx#x\n
                        xx#xxx#x\n
                        xx#xxx#x\n"
            )
        ),
        (
            'o',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        x#######\n
                        #xxxxxx#\n
                        #xxxxxx#\n
                        #xxxxxx#\n
                        xx#####x\n"
            )
        ),
        (
            'p',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        #####xxx\n
                        #xxx#xxx\n
                        #####xxx\n
                        #xxxxxxx\n
                        #xxxxxxx\n"
            )
        ),
        (
            'q',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        xxxx####\n
                        xxxx#xx#\n
                        xxxx####\n
                        xxxxxxx#\n
                        xxxxxxx#\n"
            )
        ),
        (
            'r',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        x#x###xx\n
                        x##xxxxx\n
                        x#xxxxxx\n
                        x#xxxxxx\n
                        x#xxxxxx\n"
            )
        ),
        (
            's',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        x#######\n
                        #xxxxxxx\n
                        x######x\n
                        xxxxxxx#\n
                        #######x\n"
            )
        ),
        (
            't',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        xx#xxxxx\n
                        ######xx\n
                        xx#xxxxx\n
                        xx#xxxx#\n
                        xxx####x\n"
            )
        ),
        (
            'u',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        #xxxxxx#\n
                        #xxxxxx#\n
                        #xxxxxx#\n
                        x#xxxx#x\n
                        xx####xx\n"
            )
        ),
        (
            'v',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        #xxxxxx#\n
                        x#xxxxx#\n
                        xx#xxx#x\n
                        xxx#x#xx\n
                        xxxx#xxx\n"
            )
        ),
        (
            'w',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        #xxxxxx#\n
                        x#xxxxx#\n
                        x#xx#xx#\n
                        xx##x##x\n
                        xx##xx#x\n"
            )
        ),
        (
            'x',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        ###xxxx#\n
                        xxx#xx#x\n
                        xx#x##xx\n
                        x#xxxx#x\n
                        #xxxxxx#\n"
            )
        ),
        (
            'y',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        #xxxxxx#\n
                        #xxxxxx#\n
                        x#######\n
                        xxxxxxx#\n
                        xxxxxxx#\n"
            )
        ),
        (
            'z',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        ########\n
                        xxxxxx#x\n
                        xxxx#xxx\n
                        x##xxxxx\n
                        ########\n"
            )
        ),
        (
            'ä',
            Bitmap::from(
                "x#xxxx#x\n
                        xxxxxxxx\n
                        #######x\n
                        xxxxxxx#\n
                        ########\n
                        #xxxxxx#\n
                        ########\n"
            )
        ),
        (
            'ö',
            Bitmap::from(
                "xxxxxxxx\n
                        x#xxxx#x\n
                        #xxxxxxx\n
                        ########\n
                        #xxxxxx#\n
                        #xxxxxx#\n
                        ########\n"
            )
        ),
        (
            ' ',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        xxxxxxxx\n
                        xxxxxxxx\n
                        xxxxxxxx\n
                        xxxxxxxx\n
                        xxxxxxxx\n"
            )
        ),
        (
            '\n',
            Bitmap::from(
                "xxxxxxxx\n
                        xxxxxxxx\n
                        xxxxxxxx\n
                        xxxxxxxx\n
                        xxxxxxxx\n
                        xxxxxxxx\n
                        xxxxxxxx\n"
            )
        )
    ]);
}
#[derive(Clone)]
pub struct Bitmap {
    pub map: HashMap<(i32, i32), char>,
}
impl Bitmap {
    pub fn new() -> Bitmap {
        Bitmap {
            map: HashMap::new(),
        }
    }
    pub fn from(input_string: &str) -> Bitmap {
        let mut char_map: HashMap<(i32, i32), char> = HashMap::new();
        let mut row = 0;
        let mut i = 0;
        for (index, character) in input_string.chars().enumerate() {
            i += 1;
            if character == '\n' {
                i = 0;
                row += 1;
            }
            let position = (i as i32, row as i32);
            char_map.insert(position, character);
        }
        Bitmap { map: char_map }
    }
}
